# Generated by Django 5.0.4 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='geo_id',
            field=models.CharField(blank=True, null=True, verbose_name='Geographic Data ID'),
        ),
        migrations.AlterField(
            model_name='historicalfarmparcel',
            name='geo_id',
            field=models.CharField(blank=True, null=True, verbose_name='Geographic Data ID'),
        ),
    ]
