# Generated by Django 5.0.4 on 2026-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0008_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfarmparcel',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
