# Generated by Django 5.0.4 on 2026-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0009_alter_farmparcel_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='End-season coefficient (Irrigation)'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='kc_init',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Init-season coefficient (Irrigation)'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mid-season coefficient (Irrigation)'),
        ),
        migrations.AddField(
            model_name='historicalfarmcrop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='End-season coefficient (Irrigation)'),
        ),
        migrations.AddField(
            model_name='historicalfarmcrop',
            name='kc_init',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Init-season coefficient (Irrigation)'),
        ),
        migrations.AddField(
            model_name='historicalfarmcrop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mid-season coefficient (Irrigation)'),
        ),
    ]
