# Generated by Django 5.0.4 on 2025-07-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0005_observation_sensor_id'),
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldPredictionObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.observation')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmcrop')),
            ],
            options={
                'verbose_name': 'Yield Prediction Observation',
                'verbose_name_plural': 'Yield Prediction Observations',
            },
            bases=('farm_activities.observation',),
        ),
    ]
