# Generated by Django 5.0.4 on 2025-07-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0007_set_observations_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('major', 'Major'), ('critical', 'Critical')], default='moderate', max_length=255, verbose_name='Severity')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
            bases=('farm_activities.farmcalendaractivity',),
        ),
    ]
