# Generated by Django 5.0.4 on 2025-08-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0008_alert'),
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetectionObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.observation')),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Has Area')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel', verbose_name='Has Parcel')),
            ],
            options={
                'verbose_name': 'Disease Detection Observation',
                'verbose_name_plural': 'Disease Detection Observations',
            },
            bases=('farm_activities.observation',),
        ),
        migrations.CreateModel(
            name='SprayingRecommendationObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.observation')),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Has Area')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel', verbose_name='Has Parcel')),
                ('pesticide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_management.pesticide')),
            ],
            options={
                'verbose_name': 'Spraying Recommendation Observation',
                'verbose_name_plural': 'Spraying Recommendation Observations',
            },
            bases=('farm_activities.observation',),
        ),
        migrations.CreateModel(
            name='VigorEstimationObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.observation')),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Has Area')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel', verbose_name='Has Parcel')),
            ],
            options={
                'verbose_name': 'Vigor Estimation Observation',
                'verbose_name_plural': 'Vigor Estimation Observations',
            },
            bases=('farm_activities.observation',),
        ),
        migrations.CreateModel(
            name='YieldPredictionObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.observation')),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Has Area')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel', verbose_name='Has Parcel')),
            ],
            options={
                'verbose_name': 'Yield Prediction Observation',
                'verbose_name_plural': 'Yield Prediction Observations',
            },
            bases=('farm_activities.observation',),
        ),
    ]
