# Generated by Django 5.0.4 on 2025-08-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0009_diseasedetectionobservation_and_more'),
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcalendaractivity',
            name='parcel_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel', verbose_name='Has Parcel'),
        ),
    ]
