# Generated by Django 5.0.4 on 2025-08-25 17:53

from django.db import migrations


MODELS_TO_FIX_attr_map = {
    'DiseaseDetectionObservation': 'parcel',
    'SprayingRecommendationObservation': 'parcel',
    'VigorEstimationObservation': 'parcel',
    'YieldPredictionObservation': 'parcel',
    'FertilizationOperation': 'operated_on',
    'IrrigationOperation': 'operated_on',
    'CropProtectionOperation': 'operated_on',
}

def copy_parcel_to_temp(apps, schema_editor, model_name, attr_name):
    SomeActivityModel = apps.get_model('farm_activities', model_name)
    FarmCalendarActivity = apps.get_model('farm_activities', 'FarmCalendarActivity')

    for m_instance in SomeActivityModel.objects.all():
        parcel = getattr(m_instance, attr_name)
        if parcel:
            parent = FarmCalendarActivity.objects.get(id=m_instance.farmcalendaractivity_ptr_id)
            parent.parcel_temp = parcel
            parent.save()


def reverse_copy(apps, schema_editor, model_name, attr_name):
    SomeActivityModel = apps.get_model('farm_activities', model_name)
    FarmCalendarActivity = apps.get_model('farm_activities', 'FarmCalendarActivity')

    for activity in FarmCalendarActivity.objects.filter(parcel_temp__isnull=False):
        try:
            m_instance = SomeActivityModel.objects.get(farmcalendaractivity_ptr_id=activity.id)
            setattr(m_instance, attr_name, activity.parcel_temp)
            m_instance.save()
            activity.parcel = None
            activity.save()
        except SomeActivityModel.DoesNotExist:
            pass


def operation(apps, schema_editor):
    for model_name, attr_name in MODELS_TO_FIX_attr_map.items():
        print(f'processing {model_name} - {attr_name}')
        copy_parcel_to_temp(apps, schema_editor, model_name, attr_name)


def reverse_op(apps, schema_editor):
    for model_name, attr_name in MODELS_TO_FIX_attr_map.items():
        reverse_copy(apps, schema_editor, model_name, attr_name)


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0010_farmcalendaractivity_parcel_temp'),
    ]

    operations = [
        migrations.RunPython(operation, reverse_op),
    ]



