# Generated by Django 5.0.4 on 2025-08-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0011_copy_parcel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropprotectionoperation',
            name='operated_on',
        ),
        migrations.RemoveField(
            model_name='diseasedetectionobservation',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='fertilizationoperation',
            name='operated_on',
        ),
        migrations.RemoveField(
            model_name='irrigationoperation',
            name='operated_on',
        ),
        migrations.RemoveField(
            model_name='sprayingrecommendationobservation',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='vigorestimationobservation',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='yieldpredictionobservation',
            name='parcel',
        ),
    ]
