# Generated by Django 5.0.4 on 2025-08-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0012_remove_cropprotectionoperation_operated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmcalendaractivity',
            old_name='parcel_temp',
            new_name='parcel',
        ),
    ]
