# Generated by Django 5.0.4 on 2025-10-07 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0013_rename_parcel_temp_farmcalendaractivity_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcalendaractivity',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
