# Generated by Django 5.0.4 on 2026-02-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0014_alter_farmcalendaractivity_start_datetime'),
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalActivity',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_management.farmanimal')),
            ],
            options={
                'verbose_name': 'Animal Activity',
                'verbose_name_plural': 'Animal Activities',
            },
            bases=('farm_activities.farmcalendaractivity',),
        ),
    ]
