# Generated by Django 5.0.4 on 2026-04-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0015_animalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLactatingActivity',
            fields=[
                ('animalactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.animalactivity')),
                ('days_in_milk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lactation_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('control', models.CharField(max_length=255)),
                ('total_milk_yield_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_milk_yield_unit', models.CharField(max_length=255)),
                ('milk_yield_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('milk_yield_unit', models.CharField(max_length=255)),
                ('rcs_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rcs_unit', models.CharField(max_length=255)),
                ('urea_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urea_unit', models.CharField(max_length=255)),
                ('fat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat_unit', models.CharField(max_length=255)),
                ('protein_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein_unit', models.CharField(max_length=255)),
                ('dry_matter_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dry_matter_unit', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Animal Lactating Activity',
                'verbose_name_plural': 'Animal Lactating Activities',
            },
            bases=('farm_activities.animalactivity',),
        ),
    ]
